version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_DB: zoonoses_estoque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./controle-estoque-zoonoses-api
    container_name: backend-zoonoses
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/zoonoses_estoque
    volumes:
      - ./controle-estoque-zoonoses-api:/app

  frontend:
    build:
      context: ./controle-estoque-zoonoses-frontend
    container_name: frontend-zoonoses
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./controle-estoque-zoonoses-frontend:/app

volumes:
  postgres-data:
